modLoader="javafml"
loaderVersion="[43,)"
license="GNU General Public License v3.0"

[[mods]]
modId="immersiverevolution"
version="0.0.1-1.19.2"
displayName="Immersive Revolution"
logoFile="immersiverevolution.png"
authors="Laidlow"
description='''
Inspired by Rockhounding Mod: Chemistry, Immersive Intelligence and HBM, Immersive Revolution is an Immersive Engineering addon focused around nuclear energistics and long, complex crafting processes.
Welcome to the real power plant! This is how we feeding our factories!
'''

[[dependencies.immersiverevolution]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.immersiverevolution]]
    modId="immersiveengineering"
    mandatory=true
    versionRange="[1.19.2-9.2.2-165]"
    ordering="NONE"
    side="BOTH"

[[dependencies.immersiverevolution]]
    modId="jei"
    mandatory=true
    versionRange="[11.6.0.1016]"
    ordering="NONE"
    side="BOTH"

[[dependencies.immersiverevolution]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
